const express = require("express");
const _ = express.Router();
const { customError } = require("../lib/CustomError");
const categoryRoutes = require("./api/Category.api");
const subcategoryRoutes = require("./api/subCategory.api");
const brandRoutes = require("./api/brand.api");
const productRoutes = require("./api/product.api");
const variantRoutes = require("./api/variant.api");
const discountRoutes = require("./api/discount.api");
const roleRoutes = require("./api/role.api");
const userRoutes = require("./api/user.api");
const permissionRoutes = require("./api/permisson.api");
const cupuonRoutes = require("./api/coupon.api");
const cartRoutes = require("./api/cart.api");
const wishListRoutes = require("./api/wishList.api");
const deliveryChargeRoutes = require("./api/deliveryCharge.api");
const orderRoutes = require("./api/order.api");
const paymentRoutes = require("./api/payment.api");
const smsRoutes = require("./api/sms.api");
const merchantRoutes = require("./api/merchant.api");
const courierRoutes = require("./api/courier.api");
const stockAdjustRoutes = require("./api/stockAdjust.api");
const purchaseRoutes = require("./api/purchase.api");
const sizeChartRoutes = require("./api/sizeChart.api");

_.use("/auth", userRoutes);
_.use(categoryRoutes);
_.use(subcategoryRoutes);
_.use(brandRoutes);
_.use("/product", productRoutes);
_.use(variantRoutes);
_.use(discountRoutes);
_.use(roleRoutes);
_.use("/permission", permissionRoutes);
_.use("/coupon", cupuonRoutes);
_.use("/cart", cartRoutes);
_.use("/wishList", wishListRoutes);
_.use("/delivery-charge", deliveryChargeRoutes);
_.use("/order", orderRoutes);
_.use("/payment", paymentRoutes);
_.use("/sms", smsRoutes);
_.use("/merchant", merchantRoutes);
_.use("/courier", courierRoutes);
_.use("/stock", stockAdjustRoutes);
_.use("/purchase", purchaseRoutes);
_.use("/sizechart", sizeChartRoutes);
_.use("/sales-return", require("./api/salesReturn.api"));
_.use("/byretrun-Sale", require("./api/byretrunSale.api"));
_.use("/transaction-category", require("./api/transitionCategory.api"));
_.use("/account", require("./api/account.api"));
_.use("/transaction", require("./api/createTransaction.api"));
_.use("/moneytransfer", require("./api/moneyTransfer.api"));
_.use("/fundhandover", require("./api/fundhandover.api"));
_.use("/invoice", require("./api/invoice.api"));
_.route("*").all(() => {
  throw new customError("Route not found", 404);
});
module.exports = _;
