const express = require("express");
const _ = express.Router();
const { customError } = require("../lib/CustomError");
const categoryRoutes = require("./api/Category.api");
const subcategoryRoutes = require("./api/subCategory.api");
const brandRoutes = require("./api/brand.api");
const productRoutes = require("./api/product.api");
const variantRoutes = require("./api/variant.api");
const discountRoutes = require("./api/discount.api");
const roleRoutes = require("./api/role.api");
const userRoutes = require("./api/user.api");
const permissionRoutes = require("./api/permisson.api");
const cupuonRoutes = require("./api/coupon.api");
const cartRoutes = require("./api/cart.api");
const wishListRoutes = require("./api/wishList.api");
const deliveryChargeRoutes = require("./api/deliveryCharge.api");
const orderRoutes = require("./api/order.api");
_.use("/auth", userRoutes);
_.use(categoryRoutes);
_.use(subcategoryRoutes);
_.use(brandRoutes);
_.use("/product", productRoutes);
_.use(variantRoutes);
_.use(discountRoutes);
_.use(roleRoutes);
_.use("/permission", permissionRoutes);
_.use("/coupon", cupuonRoutes);
_.use("/cart", cartRoutes);
_.use("/wishList", wishListRoutes);
_.use("/delivery-charge", deliveryChargeRoutes);
_.use("/order", orderRoutes);
_.route("*").all(() => {
  throw new customError("Route not found", 404);
});
module.exports = _;
