name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/zcommerce
            # pull the code from the repository
            git pull origin main

            # depencencies install
            npm install --production

            # PM2 process restart or start

            pm2 restart all || (pm2 start index.js --name "zcommerce-backend" && pm2 start npm --name "zcommerce-worker" -- run worker:image)

            # save the PM2 process list
            pm2 save
